### ISSUE TITLE
Problems with http requests from Laravel using pusher config

### ISSUE THREAD

**Issue by maciejszpyra** [tlaverdure/laravel-echo-server#130]
I set up laravel-echo-server using laravel pusher config and everything is ok.
When I tried implement this setup on production it dosen't work .

 Users connect and authenticate to laravel-echo-server just fine but it seems there is no connection between laravel and echo server when it comes to consuming events in queue I get failed job and ` Illuminate\Broadcasting\BroadcastException`.

When I try https://myhost:6001/apps/app-id/channels?auth_key=auth_key I'm getting proper response. Any ideas why this is happening and how to fix it? 

EDIT:
I changed driver to redis and it works so problem is with sending request via https?

**Comment by barryvdh** [comment]
Did you setup your config correctly, with the pusher keys?

**Comment by pedrogaldino** [comment]
I'm having same issue.

Laravel get Illuminate\Broadcasting\BroadcastException when try to connect via https to my production server. The exception return a empty message.

**Comment by chancezeus** [comment]
Came across this issue too when trying to use the http endpoint (there are multiple laravel sites on the server and since the redis broadcaster can not distinguish between them, broadcast events might go to the wrong user)...

Finally solved it:
in the options (either hard-coded or through .env) set the following:
```
'options' => [
    'host' => 'THE_HOST_NAME_THAT_MATCHES_THE_CN_IN_THE_SSL_CERTIFICATE',
    'scheme' => 'https',
    'port' => 'THE_PORT_THAT LARAVEL ECHO SERVER LISTENS ON'
]
```

do not forget to restart the queue (for me a `php artisan queue:restart` was not enough to properly clear the config, I had to actually restart the process itself (through supervisorctl restart))

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
