### ISSUE TITLE
Android Client 

### ISSUE THREAD

**Issue by dipit2007** [tlaverdure/laravel-echo-server#148]
is there any Android Client for Laravel Echo Server?

**Comment by Skintillion** [comment]
This is the server, not the client (I made the same mistake)

you want https://github.com/laravel/echo

**Comment by dipit2007** [comment]
I know this is server and also aware of https://github.com/laravel/echo. But I need Android Version of https://github.com/laravel/echo . So please help me.

**Comment by barryvdh** [comment]
https://github.com/socketio/socket.io-client-java is a Java port of Socketio. 
You just have to add the echo logic there.

**Comment by dipit2007** [comment]
Thanks I have also used https://github.com/socketio/socket.io-client-java . Can you please share Echo client implementation document (if available) ? So that I can write code for own requirement.

**Comment by barryvdh** [comment]
No but you can look at the code in the echo repo

**Comment by dipit2007** [comment]
Ok Thanks a lot.

**Comment by enzonotario** [comment]
Hi @dipit2007 do you have any advance about this? I need it and want to know if you have and can share your work... Thanks!

**Comment by dipit2007** [comment]
Yes started but not completed yet due to lack of time. will share once its completed.

**Comment by enzonotario** [comment]
Nice! I will try to do something meanwhile, but I would love to see your work when you finished it and compare. Thanks!

**Comment by dipit2007** [comment]
@enzonotario  Hello friend, any update on your project?

**Comment by enzonotario** [comment]
Hi @dipit2007 

Sorry but no. We change from native android to ionic, so we left it.

Although we have an active native project, but it's on Pusher. Maybe we will work on it later. I'll send you a massage if it is accomplished.

Greets.

**Comment by dipit2007** [comment]
Thanks

**Comment by enzonotario** [comment]
Hi @dipit2007 I have a little advance on this, using the library https://github.com/socketio/socket.io-client-java

Firstly, I don't know so much of android, so I'm sure that it can be improve. Moreover, the "subscribed event" never occurs, but it works, so maybe you or anyone here can help us. 

I only use private channels, and it's working with auth throw laravel-jwt

The code is:

```
public void startEcho() {
        Log.e(TAG, "ECHO START...");
        
        try {
            socket = IO.socket("http://192.168.1.5:6001");

            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.e(TAG, "ECHO CONNECTED");
                }
            }).on("App\\Events\\NotificationCreated", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.e(TAG, "ECHO NOTIFICATION CREATED");
                }
            }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.e(TAG, "ECHO DISCONNECTED");
                }
            });

            socket.connect();

            JSONObject object = new JSONObject();
            JSONObject auth = new JSONObject();
            JSONObject headers = new JSONObject();

            try {
                object.put("channel", "private-user.2");
                object.put("name", "subscribe");

                headers.put("Authorization", "Bearer " + sessionManager.getToken());
                auth.put("headers", headers);
                object.put("auth", auth);
            } catch (JSONException e) {
                e.printStackTrace();
            }

            socket.emit("subscribe", object, new Ack() {
                @Override
                public void call(Object... args) {
                    Log.e(TAG, "ECHO SUBSCRIBED"); // This event never occurs. I don't know why...
                }
            });
        } catch (URISyntaxException e) {
            Log.e(TAG, "ECHO ERROR");
            e.printStackTrace();
        }
    }
```

I did it the last night, so I didn't test it so much. Please, take a look and give me a feedback, thanks!

Hope this can help you.

**Comment by dipit2007** [comment]
ohh I did same way to work around. can we work together to make it complete and usable for all?

**Comment by enzonotario** [comment]
I don't think that can do a "library" port of echo-client to android, since I don't know so much Java. I only worked in an project and so far I will no work on any other java project. But, if I can help you in anything, excellent!

Moreover, I don't speak english (as you can see). So for me is so hard to work with another english-speaker people (I know that I have to study more)...

Do you have your piece of code to share? or any repo? Thanks.

**Comment by laggards** [comment]
@enzonotario can you say more about how to emit event with echo in andorid.

**Comment by enzonotario** [comment]
Hi @laggards !
What is your issue? to emit event you have to do it in the same way as if you client were the original javascript client.
The android client will receive it.

But, if you're asking about client-events (https://laravel.com/docs/5.4/broadcasting#client-events) I don't know how to do that since I never had to use it.

I just implemented the "simple flow": the server emits and the client receives the event. To receive the events I use the code that I put above.

Hope it helps you!

**Comment by kevinp1005** [comment]
@laggards so.. did you find a way to emit from android using echo server ?

**Comment by kevinp1005** [comment]
@enzonotario it works! but I couldn't emit back to the server? I can listen to the events on android but couldn't emit back

**Comment by enzonotario** [comment]
Hi @kevinp1005 . I never use echo to emit events from the client to the server. My workflow is that the client make an http request to the API and the API emits some events in any time to the client, so I don't know how can you approach this.

Anyway, did you try using `socket.emit()` function ?

**Comment by enzonotario** [comment]
Well, I'm sorry but I can't help you since I have never implemented that workflow.

Anyway, I don't think that there are differences in making HTTP requests or emitting throw websockets when the events will be every minute. I think that the same payload (and its size) will be sended from the client. Maybe more or less megabytes, but I don't think that it matters.

**Comment by kevinp1005** [comment]
@enzonotario Ah okay maybe I'll try that again and let you know if I can find anything.

Yes, I would call it every minute or every five minutes if I have to use HTTP request, but if I could get the socket communication between Android and echo server working properly(which right now I don't know how to emit to the server) I would call it every second. Anyway, it's just for server performance that's why I consider using socket instead of HTTP for this part.

**Comment by dipit2007** [comment]
wow really happy that people are working what i raised long back. Can you people share code so that I can also contribute to all.

**Comment by dipit2007** [comment]
@kevinp1005 what is your requirement? please share.

**Comment by zahid--ali** [comment]
@enzonotario  I am trying to use your code but on server side I get authentication error. HTTP 302 error which is directing me to new page. 
My backend developer is using Laravel Echo Server and he asked me about CRSF-Token so do I need to pass it in the auth or what?

**Comment by enzonotario** [comment]
Hi! As I understand, the csrf token is not for use with apis, only for conventional forms. So I think that your backend developer has to disable it.
If you need an auth system you could use jwt.

**Comment by erlangp** [comment]
thanks @enzonotario :+1:

**Comment by Ewrei** [comment]
@enzonotario
Hello, you have done a great job. I was able to connect to my server, and I see that the server is sending data back.
But I don't understand how you get them on the client side. Also, nothing comes up in the logs ((
