### ISSUE TITLE
[question] reverse proxy with nginx

### ISSUE THREAD

**Issue by sald19** [tlaverdure/laravel-echo-server#184]
Hi, i am try set laravel echo server behind a  reverse proxy with nginx. i got this error

app url: `laravel.app`
laravel echo server: `io.laravel.app`
 i am use Homestead with laravel 5.4

![bzxn7lv](https://user-images.githubusercontent.com/1674971/28146713-1ce7fc84-6739-11e7-9771-f2f4ee7c3b7e.png)

with `"devMode": true` 
![wxynrnv](https://user-images.githubusercontent.com/1674971/28146723-3847789c-6739-11e7-94f9-1dd2ac94d95b.png)

this is my config in `laravel-echo-server.json`
![tiij0p1](https://user-images.githubusercontent.com/1674971/28146760-8b9e39cc-6739-11e7-80db-82be00cf0908.png)

laravel echo config
![vwobjpz](https://user-images.githubusercontent.com/1674971/28146806-f1045f9e-6739-11e7-89ca-1c95c9f089ee.png)

this is `io.laravel.app` virtualHost
![yyy377k](https://user-images.githubusercontent.com/1674971/28146938-848aee04-673a-11e7-8901-4c28223d3c62.png)

**Comment by nguyenhaiphan** [comment]
This problem related to the cross domain issues. I got this too when I try to use ngrok service to test my local enviroment (one domain for app, one domain for the socket). You can enable the develop mode on the json config file to find out what the problem is. To me, it seem to be the kind of TokenMismatchException, I did try to bypass it on VerifyCsrfToken.php with the exception for broadcast/auth, but then i got the HttpException.

**Comment by sald19** [comment]
solved with share Cookie domain

in `config/session.php` set 

```php
'domain' => '.laravel.com',  //keep the dot
```

**Comment by tlaverdure** [comment]
@sald19 so you were able to bypass CSRF by setting your domain to something like `.laravel`? 

If this fixes your issue can we close this?
