### ISSUE TITLE
How configure laravel-echo-server to a multi-tenant context

### ISSUE THREAD

**Issue by touchinformatica** [tlaverdure/laravel-echo-server#185]
Hi everyone!

I'm have some difficulties in implement websockets notification in a multi-tenant context.
The great problem are in change authHost for each tenant. 

I need to change authHost to my various subdomains, where each subdomain is a tenant:
foo.myapp.com 
asd.myapp.com

How i can do this in runtime?

Sorry for my poor English!!

**Comment by touchinformatica** [comment]
Hi folks!

I made it work!

Stay here my suggestion for the newest versions of server.  
I edited the files of private channel of laravel-echo-server to allow receive the authentication host from the listen request:

```
PrivateChannel.prototype.authenticate = function (socket, data) {
	let authHost = (data.auth && data.auth.host) ? data.auth.host : this.authHost();
        var options = {
            url: authHost + this.options.authEndpoint,
            form: { channel_name: data.channel },
            headers: (data.auth && data.auth.headers) ? data.auth.headers : {},
            rejectUnauthorized: false
        };
        return this.serverRequest(socket, options);
    };
```

and in my instance of Echo in client side:

```
window.Echo = new Echo({
    broadcaster: 'socket.io',	
    host: '127.0.0.1:6001',
    auth:
    {
        headers:
        {
            'Authorization' : 'Bearer ' + localStorage.getItem("satellizer_token")            
        },
	host : window.location.origin
    }    
});
```

Thanks!!!

**Comment by tobiasvielmetter** [comment]
@touchinformatica I have the same issue, except I am not using stateless authentication but session authentication, so my session actually does not authenticate because it doesnt get to the right subdomain (if I get this right). In your case, since you are using token based stateless auth, you could just have a authentication subdomain that is only reacting to the authentication.
I had a similar idea like you did, with changing the authHost, except that I thought I could use the referer header instead of adding an additional parameter for the desired host. this would require a allowAuthSubdomains option in the laravel-echo-server.json to be activated. This way the proper subdomain would be passed via referer:

```
        //require at top of file
        var url = require('url');

        // in PrivateChannel.prototype.authenticate
        authHost = this.authHost();
        if(this.options.allowAuthSubdomains)
        {
            var referer = url.parse(socket.request.headers.referer);
            var authHost = referer.protocol+"//"+referer.host;
            if(referer.hostname.substr( referer.hostname.indexOf('.') + 1 )!==this.authHost())
                authHost = this.authHost();
        }
        
        var options = {
            url: authHost + this.options.authEndpoint,
            form: { channel_name: data.channel },
            headers: (data.auth && data.auth.headers) ? data.auth.headers : {},
            rejectUnauthorized: false
        };
```

I am wondering if it is possible to circumvent authentication by spoofing either the referer or the custom parameter you suggested to another server. Maybe i am missing something. Still figuring this out. Thats why I have introduced all these conditions, not sure they are waterproof though. Anyone having more insight on this?

**Comment by touchinformatica** [comment]
@tobiasvielmetter  thank you very much!! 
Worked perfectly and much better than my approach.

**Comment by tobiasvielmetter** [comment]
@touchinformatica glad it helped you. It's working for me as well, but obviously it would be nice to have this kind of flexibility without altering the package. Maybe the active package author/s @tlaverdure @barryvdh are willing to consider?

Also I have another version, that would not require a additional allowAuthSubdomains option anymore. With this version it would be enough to use the usual nginx wildcard syntaxt, e.g. authHost: '.myapp.com' (see dot before domain). In case the referer minus the subdomain, but with the dot matches authHost, it will allow the cleaned referer as authHost:
```
        //require at top of file
        var url = require('url');

        // in PrivateChannel.prototype.authenticate
        var authHost = this.authHost();
        var referer = url.parse(socket.request.headers.referer);
        if(referer.hostname.substr( referer.hostname.indexOf('.'))===this.authHost())
                authHost = referer.protocol+"//"+referer.host;
        
        var options = {
            url: authHost + this.options.authEndpoint,
            form: { channel_name: data.channel },
            headers: (data.auth && data.auth.headers) ? data.auth.headers : {},
            rejectUnauthorized: false
        };
```

**Comment by tlaverdure** [comment]
I don't see any immediate issues with this. Would you mind sending a PR so I can see a diff?

Thanks

**Comment by tobiasvielmetter** [comment]
@tlaverdure will do, thanks

**Comment by touchinformatica** [comment]
@tobiasvielmetter particularly, I prefer your aprroach #1.  I think it's more clear to put the configuration of the subdomain inside the laravel-echo-server.json file.

**Comment by tlaverdure** [comment]
https://github.com/tlaverdure/laravel-echo-server/pull/190 should close this issue.

**Comment by mdixon18** [comment]
Hi There,

So it is not possible to set the URL on the client end e.g.

```
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://127.0.0.1:6001',
    auth: {
        headers: {
            Authorization: 'Bearer ' + APP_KEY
        },
        host : window.location.origin
    },
});
```

I think this would be incredibly useful when using an application that will be used on multiple servers.

My hostname is test.dev but the echo server is responding with Invalid URI "127.0.0.1/broadcasting/auth" when i send the above request.

**Comment by chamindaindika** [comment]
Hi guys, I was struggling to make the laravel echo server works for multi tenants. In my case, there was no referer set to the socket object (socket.request.headers.referer). Because of that, according to the below code block in **private-channel.ts** authHost function, all the time it selects the first domain as the authHost which is defined in the laravel echo server config.

> 
        let authHostSelected = authHosts[0] || 'http://localhost';

        if (socket.request.headers.referer) {
            let referer = url.parse(socket.request.headers.referer);

            for (let authHost of authHosts) {
                authHostSelected = authHost;

                if (this.hasMatchingHost(referer, authHost)) {
                    authHostSelected = `${referer.protocol}//${referer.host}`;
                    break;
                }
            };
        }

And this is my frontend laravel echo code related to creating the socket connection.

> 
        import Echo from 'laravel-echo';
        window.io = require('socket.io-client');

        if (typeof io !== 'undefined') {
            window.Echo = new Echo({
                broadcaster: 'socket.io',
                host:  process.env.MIX_ECHO_SERVER_PROTOCOL+'://'+window.location.hostname+':'+process.env.MIX_ECHO_SERVER_PORT,
                namespace: 'Modules.Student.Events',
                transports: ['websocket']
            });
        }

Anyone has an idea on how to fix this issue? What should I do for setting the referer into the socket object. It's been more than 2 days spent on this problem. Please advice me on sort out this.

Thanks!

**Comment by Udsupun** [comment]
Hi guys, I was struggling to make the laravel echo server works for multi tenants. In my case, there was no referer set to the socket object (socket.request.headers.referer). Because of that, according to the below code block in **private-channel.ts** authHost function, all the time it selects the first domain as the authHost which is defined in the laravel echo server config.

>
        let authHostSelected = authHosts[0] || 'http://localhost';

        if (socket.request.headers.referer) {
            let referer = url.parse(socket.request.headers.referer);

            for (let authHost of authHosts) {
                authHostSelected = authHost;

                if (this.hasMatchingHost(referer, authHost)) {
                    authHostSelected = `${referer.protocol}//${referer.host}`;
                    break;
                }
            };
        }

And this is my frontend laravel echo code related to creating the socket connection.

>
        import Echo from 'laravel-echo';
        window.io = require('socket.io-client');

        if (typeof io !== 'undefined') {
            window.Echo = new Echo({
                broadcaster: 'socket.io',
                host:  process.env.MIX_ECHO_SERVER_PROTOCOL+'://'+window.location.hostname+':'+process.env.MIX_ECHO_SERVER_PORT,
                namespace: 'Modules.Student.Events',
                transports: ['websocket']
            });
        }

Anyone has an idea on how to fix this issue? What should I do for setting the referer into the socket object. It's been more than 2 days spent on this problem. Please advice me on sort out this.

Thanks!

**Comment by catalinux** [comment]
I implemented multi-tenant by namespacing the channela. So when my app joins a channel, that channel is called

tenanta.my.pref.channel

**Comment by anwardote** [comment]
I think... The final solution as following:

//single domain
"authHost": "http://localhost",

//multiple domains, with or without protocol
"authHost": ["http://localhost", "web.server.app"],

//wildcard
"authHost": ".server.app",

//mixed domain as well as wildcard
"authHost": [".server.app", "https://web.server.app"],

**Comment by JorgenSolli** [comment]
> I think... The final solution as following:
> 
> //single domain
> "authHost": "http://localhost",
> 
> //multiple domains, with or without protocol
> "authHost": ["http://localhost", "web.server.app"],
> 
> //wildcard
> "authHost": ".server.app",
> 
> //mixed domain as well as wildcard
> "authHost": [".server.app", "https://web.server.app"],

Thank you! I had no idea this could be an array.

**Comment by pLavrenov** [comment]
//mixed domain as well as wildcard
"authHost": [".server.app", "https://server.app"],

maybe need set this to default after init ??
