### ISSUE TITLE
Server not receiving any connection from client. 

### ISSUE THREAD

**Issue by martingg88** [tlaverdure/laravel-echo-server#206]
Any idea why the server can't receive the connection from client?

Here is the setup at my apache and start the laravel-echo-server at localhost but it seems like not receive any connection from clients. Any idea what happen?

RewriteCond %{QUERY_STRING} transport=polling       [NC]
RewriteRule /(.*)           http://localhost:6001/$1 [P,QSA,L]

RewriteCond %{HTTP:Upgrade} websocket               [NC]
RewriteRule /(.*)           ws://localhost:6001/$1  [P,QSA,L]

ProxyPass           /socket   http://localhost:6001
ProxyPassReverse    /socket   http://localhost:6001

**Comment by prince30** [comment]
Did you fixed it ?

**Comment by martingg88** [comment]
no...

**Comment by edvordo** [comment]
Grave-digging, I know, but as the issue is still opened, here goes nothing in hopes it helps someone that stumbles upon this issue ..

Based on [this comment](https://github.com/socketio/socket.io/issues/1696#issuecomment-241414138) I compiled [this guide](https://github.com/edvordo/notes-and-rants/blob/master/instructions/laravel-echo-server_apache2_proxypass-conf.md).

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
