### ISSUE TITLE
Is it possible to send files through chat?

### ISSUE THREAD

**Issue by solancer** [tlaverdure/laravel-echo-server#254]
Is it possible to send files through chat socket?

**Comment by catalinux** [comment]
You must share same details. 

In laravel echo server there are 3 nodes of communication

1)  JS that runs in browser
2)  JS that runs on the server 
3)  laravel app

Communication between node 1 and 2 is made trough websocket protocol
Communication between node 2 and 3 is made trough redis webserver.

Questions
1) where from do you want to send that file to where?
2)  When you say file, you refer to a a binary file or it can be also an url?

**Comment by solancer** [comment]
Thank you for the swift reply. The idea is to use laravel-echo-server to build a chat application backend in laravel for a mobile application (iOS & Android). The mobile clients will use socket.io lib to communicate with the backend.

1. where from do you want to send that file to where?
The chat app is somewhat like telegram or whatsapp so one chat client to another (person to person) through the mobile application interface

2. When you say file, you refer to a a binary file or it can be also an url?
The app will be serving mp3, images, videos etc.. I'm planning on using s3 buckets for storage.

**Comment by skatetdieu** [comment]
As far as I understand, and I might be wrong, this service can only send text back and forth, not files. The only way possible one would think is to convert files to something like base64 text and send that text over and then build the file back up from the base64 text to a file again. 

Another way would be to upload the file to your server and send the receiving user a link to the uploaded file with the mechanism to download it from your server.  This would work except you'd also have to take great care of the files since they are not yours and they could quickly use up server hard drive space.

**Comment by tlaverdure** [comment]
This package does not support sending Blob or File objects over web sockets.

**Comment by prkikani** [comment]
Hello, How to communicate or bind this laravelEchoServer with mobile socket.io 
like how to communicate with channel and listener with socket.io like socket.on  and socket.emit ?
