### ISSUE TITLE
Laravel echo not POSTing to /broadcasting/auth using socket.io with private channels

### ISSUE THREAD

**Issue by gemasphi** [tlaverdure/laravel-echo-server#271]
When I use pusher it POSTs, but not with socket.io

This is the my echo initialization:

```
window.Echo = new Echo({
  broadcaster: 'socket.io',
  host: 'http://127.0.0.1' + ':6001',
});

```
and use:

```
window.Echo.private('everyone')
    .listen('MessageSent', function(e) {
        console.log("working");
    });
```

**Comment by dipit2007** [comment]
Hi,

Did you include Socket.IO
```
<script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>
```

Try to look into browser console if anything wrong.

Hope it will help.

**Comment by dipit2007** [comment]
Hi,

Did you include Socket.IO
```
   <script src="//{{ Request::getHost() }}:6001/socket.io/socket.io.js"></script>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
```

Try look into browser console to debug .

Hope it will help.

**Comment by gemasphi** [comment]
I have, if I use public channels with socket.io, it works.

**Comment by gemasphi** [comment]
I've found the solution, in the config I had the auth link wrong. Thanks

**Comment by Dartanjan** [comment]
I had the same issue but for a different reason. I ran `laravel-echo-server` as a docker container, as part of laradock, and since I couldn't see the log output, I didn't realize there were auth problems. It *does* POST to `/broadcasting/auth` but you won't see it in Web Console because it runs inside of express server.

The only way I could fix it is stop `laravel-echo-server` docker container and instead, run it in my app container manually. That way I could see exactly where the problems were.

I wish there was something like `laravel-echo-server restart` so I could manually hook into the log output and see if there are any errors.

**Comment by nogenem** [comment]
@Dartanjan How did u do that? I'm using Laradock too and i tried everything and nothing seens to work...

I tried running the echo-server inside workspace, outside the containers and with the container of echo-server and i keep getting 'Error: connect ECONNREFUSED 127.0.0.1:80' OR the events aren't caught by the echo-server ;/

**Comment by Dartanjan** [comment]
@nogenem Yeah, I figured that later, just run container without -d, but still it wouldn't have occurred to me because I hadn't seen any actual errors being logged anywhere. So the lesson is, with Echo server, run it without -d until it all works. :)

**Comment by alinasiri1367** [comment]
> I've found the solution, in the config I had the auth link wrong. Thanks
> Also, to anyone wondering: when using socket.io, there's no POST to /broadcasting/auth.

How do fix???
