### ISSUE TITLE
Intermittent HTTPS issue

### ISSUE THREAD

**Issue by MattPurland** [tlaverdure/laravel-echo-server#291]
Hi,

I've had a Laravel application running happily over HTTPS along with the Laravel Echo Server running over HTTPS in production mode, but I've just had an occurrence where the certificate for the Echo Server was invalid (both the application and the Echo Server use the same certificate, and the application was fine). Restarting the Echo Server service fixed it.

I was wondering if anyone else has had this happen? Unfortunately I didn't check the SSL error in the browser, just that it wasn't working.

Cheers,
Matt

**Comment by evolot** [comment]
It reoccur or just once?
 I inited my service with wrong config and error shown.Then I changed the config during the service is running ,the error remain.Finally I restarted the service, the right config autoloaded the error gone.

**Comment by creativesponge** [comment]
This just happened again, so it's happened 3 or 4 times now and the client is getting concerned.

I'm concerned this project hasn't really been updated in 2 years, so I feel a different service will have to be used.

**Comment by MattPurland** [comment]
This just happened again, so it's happened 3 or 4 times now and the client is getting concerned.

I'm concerned this project hasn't really been updated in 2 years, so I feel a different service will have to be used.

**Comment by poseidonphp** [comment]
Cannot speak to the built-in SSL capabilities, but as an alternative...
Can you proxy the websocket traffic? Instead of having the echo server listen on it's own port and implement it's own SSL, send all traffic to the main web server over the standard SSL port, then use the "proxy" module in Apache or NginX to internally redirect requests for "/socket.io" to the echo server. This keeps the traffic encrypted in transit, but does it all over the normal web traffic certificate.

Example config for NginX - in the server{} block of your web config:
```
location /socket.io {
    proxy_pass http://laravel-echo-server:6001; #could be localhost if Echo and NginX are on the same box
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```

**Comment by tlaverdure** [comment]
Something like @poseidonphp's suggestion is a good one.
